### ISSUE TITLE
Couldn‘t find any key in Redis server

### ISSUE THREAD

**Issue by ErickGSJ** [pricingassistant/mrq#208]
Hi

if use **--redis redis://127.0.0.1:6380** to start mrq-worker and mrq-run, i could not find any keys in Redis server.
redis server: **root     16286     1  0 10:41 ?        00:00:00 redis-server 127.0.0.1:6380**
mrq-worker: **mrq-worker default --redis redis://127.0.0.1:6380 --redis_prefix mrq**
mrq-run：**mrq-run --queue default --redis redis://127.0.0.1:6380 --redis_prefix mrq tasks.Fetch url http://www.google.com**

Even if i use the non-existing Redis server that MRQ tasks work fine，why?
redis server redis://127.0.0.1:6381 doesn't exist
mrq-worker: **mrq-worker default --redis redis://127.0.0.1:6381 --redis_prefix mrq**
mrq-run：**mrq-run --queue default --redis redis://127.0.0.1:6381 --redis_prefix mrq tasks.Fetch url http://www.google.com**

**Comment by sylvinus** [comment]
Hi @ErickGSJ !

That's because with regular queues, jobs are now only stored in mongodb:
https://github.com/pricingassistant/mrq/blob/master/docs/queue-performance.md#queue-types

Switch to a raw queue if you need more performance by putting them into redis (but loose some visibility in the dashboard)
