### ISSUE TITLE
Suddenly Slowness

### ISSUE THREAD

**Issue by orlandobcrra** [pricingassistant/mrq#218]
Hi, we have been using MRQ on our company since few months ago, it was going pretty good (processing like ~25 task per minute or ~30.000 per day), however it started to perform pretty slow (2 task per minute). same tasks, same code.
we delete old success tasks from all queues just in case, but still slow. 
wondering if you could provide some advice or paid support.
thanks

**Comment by maelorn** [comment]
Hello, 

We do not provide paid support. Could you share a little bit more about your setup (kind of job you are running raw or regular). Also make sure all MongoDB indexes are correctly [built](https://github.com/pricingassistant/mrq/blob/f0202b7cd5256d4d8d64927000e6e3fc780ae8a5/mrq/basetasks/indexes.py). If you need to troubleshot where the issue lies a place to start would be starting you own worker with the `--profile` flag and see where the bottleneck is.

**Comment by orlandobcrra** [comment]
Hello, 

Thanks for the response, issue was because mongodb was getting full, solved following these steps:
https://docs.mlab.com/ops/#compacting

Thanks.
