### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by iorlas** [pricingassistant/mrq#85]
I'm sorry, could not find any way to connect with you, guys.
IMO mrq is only a competitive to Celery solution. IMO your approach to job-queue is best possible right now with gevent, redis, mongodb.
But before moving from celery to mrq, I decide to inspect mrq sources and was quite surprised with some strange things. It is fine, I will throw some pull-requests and problems to discuss.
But I have some questions.
First of all, what is the status of mrq? I see that it is in Beta already(judging from setup.py). Still not ready for production but... What is about development status?

I mean, I see that dashboard has some ugly hacks and has many issues and plans, but it is clear to me that you cannot handle it by yourself. Anyway, I will write my own dashboard for celery or mrq, just because I need to see how many tasks I have in which status, grouped by queue and with ability to see it all on one screen. Seems like each task will be just a 16x16 image which color shows it's status.

What I want to know, should I spend time to migrate to this right now or it's "future" is questionable so I should stick with celery?

**Comment by sylvinus** [comment]
Hi!

Thanks for all your feedback, I'll take time tomorrow to reply to the other issues & PR you opened :)

We also think MRQ is very competitive with Celery, which we used a lot in the past! We have been using it in production for 1+ year, and a few other startups are using it live too. It is at the very core of our infrastructure so we're committed to support it as long as we are alive ;)

Still, it's definitely harder than it should be for a newcomer to the project, and we're more than willing to work on that. The fact that it doesn't readily work on latest Python because of the gevent issue is a shame, we'll fix that right away. I also look forward to seeing your ideas on the dashboard! 

So, don't just trust my words - let's see how we can integrate your ideas in the next few days and let's go from there! :)
